version: '3.8'

services:
  ragear:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ragear-service
    ports:
      - "8000:8000"
    environment:
      - RAG_SERVER_URL=http://10.10.11.141:5005
      - RAG_FRONTEND_URL=http://10.10.11.141:3000
      - RAG_TIMEOUT=25.0
      - DEFAULT_TOP_K=50
      - SYNC_CATALOG_ON_STARTUP=true
      - DEBUG=false
    restart: unless-stopped
